// A collection of seamless, embeddable SVG patterns, base64 encoded for direct use in CSS.
// These have been redesigned to be larger and more subtle to reduce eye strain, per user feedback.

// A sparse, confetti-like pattern of dots. Tile size: 80x80
export const DOTS_PATTERN = `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAiIGhlaWdodD0iODAiIHZpZXdCb3g9IjAgMCA4MCA4MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48Y2lyY2xlIGN4PSIyMCIgY3k9IjIwIiByPSIyIiBmaWxsPSJibGFjayIvPjxjaXJjbGUgY3g9IjYwIiBjeT0iNjAiIHI9IjMiIGZpbGw9ImJsYWNrIi8+PGNpcmNsZSBjeD0iNzAiIGN5PSIxMCIgcj0iMS41IiBmaWxsPSJibGFjayIvPjxjaXJjbGUgY3g9IjEwIiBjeT0iNzAiIHI9IjIuNSIgZmlsbD0iYmxhY2siLz48Y2lyY2xlIGN4PSI0MCIgY3k9IjQ1IiByPSIxIiBmaWxsPSJibGFjayIvPjwvc3ZnPg==`;

// Soft, wavy horizontal lines. Tile size: 80x80
export const LINES_PATTERN = `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAiIGhlaWdodD0iODAiIHZpZXdCb3g9IjAgMCA4MCA4MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCA0MCBRMjAsMjAgNDAsNDAgVDgwLDQwIiBzdHJva2U9ImJsYWNrIiBzdHJva2Utd2lkdGg9IjAuNSIgZmlsbD0ibm9uZSIvPjxwYXRoIGQ9Ik0wLDUwIFEyMCw3MCA0MCw1MCDVDgwLDUwIiBzdHJva2U9ImJsYWNrIiBzdHJva2Utd2lkdGg9IjAuNSIgZmlsbD0ibm9uZSIvPjwvc3ZnPg==`;

// A minimal, thin grid pattern. Tile size: 50x50
export const GEOMETRIC_PATTERN = `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHZpZXdCb3g9IjAgMCA1MCA1MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48bGluZSB4MT0iMCIgeTE9IjI1IiB4Mj0iNTAiIHkyPSIyNSIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIwLjUiLz48bGluZSB4MT0iMjUiIHkxPSIwIiB4Mj0iMjUiIHkyPSI1MCIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIwLjUiLz48L3N2Zz4=`;

// A simple scallop or arch pattern. Tile size: 60x40
export const HERRINGBONE_PATTERN = `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA2MCA0MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCAyMCBBIDMwIDMwIDAgMCAxIDYwIDIwIiBzdHJva2U9ImJsYWNrIiBzdHJva2Utd2lkdGg9IjAuNSIgZmlsbD0ibm9uZSIvPjwvc3ZnPg==`;
